title: BoGL Docs 
lang: en
description: BoGL Documentation 
repository: Aidenjn/bogl-docs

## local method ##
# theme: jekyll-rtd-theme

# debug:
#   compress: false
#   dist: true
#   shortcodes: true

## remote method ##
# remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - github-pages

# Allows manual sorting of the sidebar link order
readme_index:
  with_frontmatter: true

